### ISSUE TITLE
Windows 98 support regressed

### ISSUE THREAD

**Issue by leilei-** [abagames/rrootage#4]
I tried the latest binary release v0.24 and it gave me an error about a missing Kernel32.dll function. 
![rrerror](https://user-images.githubusercontent.com/6590431/37457494-16206f68-283a-11e8-972d-6f0539c4c284.png)

Just a quick FYI. I don't know if it's gcc related (4.7.2 is generally the last version to compile Win9X-friendly binaries)

EDIT: It'll also do the same in 95, Me and NT4 and it'll crash on Pentium processors now as well (on XP).
EDIT2: Tumiki Fighters is also affected by the SDL update as it'll silently crash. Replacing SDL.DLL with a 1.2.12 from somewhere else will get that working again.

**Comment by abagames** [comment]
Thank you for reporting the problem. I can't reproduce the problem because I don't have a Win9X environment. As for a quick fix, I'll add the link to the older version for Win9X users.

**Comment by leilei-** [comment]
FYI a lot of my testing for this involved running various older Windows in PCem.  It can also emulate a Voodoo2 3d card and is able to play the older versions.  It's helped me out on maintaining Win9X support for my own game project..
