### ISSUE TITLE
No gamepad button map for pause

### ISSUE THREAD

**Issue by nyanster** [abagames/rrootage#5]
> * Movement Arrow key / Joystick
> * Laser [Z] / Trigger 1, Trigger 4
> * Special [X] / Trigger 2, Trigger 3
> * Pause [P]

I think it'd be easy to add a mapping for gamepads and joystick buttons to also pause the game.
It could be done similarly to
https://github.com/abagames/rrootage/blob/84b6d089cd67b29fa061879f40115cbb3d6da015/src/screen.c#L976
But with a different button number.  Preferably both the start and select buttons of a gamepad.
Thus, this line
https://github.com/abagames/rrootage/blob/84b6d089cd67b29fa061879f40115cbb3d6da015/src/rr.c#L255
would look something like this:
```
if ( keys[SDLK_p] == SDL_PRESSED || btnFOO || btnBAR ) {
```

Unrelatedly, the fact that ESC quits the game is currently undocumented.  This is an easy documentation fix, though. :D

(I might be able to do a pull request for this, myself, or might not.  I'll figure it out soon!  I mostly just need to find out which button numbers are the two menu/pause buttons on the xbox one controller)

**Comment by nyanster** [comment]
> (I might be able to do a pull request for this, myself, or might not. I'll figure it out soon! I mostly just need to find out which button numbers are the two menu/pause buttons on the xbox one controller)

I couldn't figure out how to get rrootage-master to build on Ubuntu GNU/Linux, so I couldn't write a pull request.

**Comment by abagames** [comment]
Now we can use trigger 5,6,7,8,9 to pause the game.

**Comment by ghost** [comment]
Thank you! :D
